# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        '/:title'

# Setup
title:            gifs
tagline:          'a private collection'
description:      'a private collection'
url:              http://tilde.club/~qrush

author:
  name:           'Nick Quaranto'
  url:            https://twitter.com/qrush

paginate:         10

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/qrush/gifs

exclude: gifs
